"""add invoice_items in model

Revision ID: 16f95a934f64
Revises: 5259ae4ce1da
Create Date: 2025-01-13 22:33:39.813254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16f95a934f64'
down_revision: Union[str, None] = '5259ae4ce1da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.add_column('invoices', sa.Column('invoice_type_id', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('total_before_tax', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('total_after_tax', sa.Float(), nullable=True))
    op.drop_column('invoices', 'total_amount')
    op.drop_column('invoices', 'items')
    op.drop_column('invoices', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('items', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'total_after_tax')
    op.drop_column('invoices', 'total_before_tax')
    op.drop_column('invoices', 'invoice_type_id')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    # ### end Alembic commands ###
