"""add new column code in invoice types

Revision ID: 2ac08fed6348
Revises: 7009e025339a
Create Date: 2025-01-15 11:03:13.388421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac08fed6348'
down_revision: Union[str, None] = '7009e025339a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_types', sa.Column('code', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'invoice_types', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_types', type_='unique')
    op.drop_column('invoice_types', 'code')
    # ### end Alembic commands ###
