"""add created_at and updated_at in intermediary table of invoice  and invoice items in model

Revision ID: 4182557096aa
Revises: ca3bde635fac
Create Date: 2025-01-13 22:44:07.932044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4182557096aa'
down_revision: Union[str, None] = 'ca3bde635fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items_association', sa.Column('created_at', sa.TIMESTAMP(), nullable=False))
    op.add_column('invoice_items_association', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items_association', 'updated_at')
    op.drop_column('invoice_items_association', 'created_at')
    # ### end Alembic commands ###
