"""modify-invoice-model-v2

Revision ID: 5093b81adf3d
Revises: 3011c47564ee
Create Date: 2024-12-16 23:50:46.952509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5093b81adf3d'
down_revision: Union[str, None] = '3011c47564ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('order_id', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('invoices', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('shipping_cost', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('outstanding_balance', sa.Float(), nullable=True))
    op.add_column('invoices', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('updated_at', sa.TIMESTAMP(), nullable=False))
    op.alter_column('invoices', 'items',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('invoices', 'seller_phone')
    op.drop_column('invoices', 'remarks')
    op.drop_column('invoices', 'tax_amount')
    op.drop_column('invoices', 'tax_rate')
    op.drop_column('invoices', 'buyer_phone')
    op.drop_column('invoices', 'seller_address')
    op.drop_column('invoices', 'seller_tax_id')
    op.drop_column('invoices', 'buyer_tax_id')
    op.drop_column('invoices', 'payee')
    op.drop_column('invoices', 'bank_account')
    op.drop_column('invoices', 'payment_method')
    op.drop_column('invoices', 'bank_name')
    op.drop_column('invoices', 'seller_name')
    op.drop_column('invoices', 'total_amount_in_words')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('total_amount_in_words', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('seller_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('bank_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('bank_account', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('payee', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('buyer_tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('seller_tax_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('seller_address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('buyer_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('tax_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('seller_phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('invoices', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('invoices', 'total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('invoices', 'items',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('invoices', 'updated_at')
    op.drop_column('invoices', 'notes')
    op.drop_column('invoices', 'outstanding_balance')
    op.drop_column('invoices', 'shipping_cost')
    op.drop_column('invoices', 'discount')
    op.drop_column('invoices', 'amount')
    op.drop_column('invoices', 'unit_price')
    op.drop_column('invoices', 'quantity')
    op.drop_column('invoices', 'order_id')
    # ### end Alembic commands ###
