"""change_invoice_number_to_not_unique

Revision ID: 695b04f4156e
Revises: 994de06d1bca
Create Date: 2025-01-14 01:44:53.030855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695b04f4156e'
down_revision: Union[str, None] = '994de06d1bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoices_invoice_number_key', 'invoices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('invoices_invoice_number_key', 'invoices', ['invoice_number'])
    # ### end Alembic commands ###
