"""fix_invoice_type_foreign_key

Revision ID: 994de06d1bca
Revises: a6920466afa3
Create Date: 2025-01-13 23:46:47.637167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994de06d1bca'
down_revision: Union[str, None] = 'a6920466afa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invoice_items_invoice_id_fkey', 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'invoice_id')
    op.drop_constraint('invoices_invoice_type_id_fkey', 'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'invoice_types', ['invoice_type_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_invoice_type_id_fkey', 'invoices', 'invoices', ['invoice_type_id'], ['id'], ondelete='CASCADE')
    op.add_column('invoice_items', sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('invoice_items_invoice_id_fkey', 'invoice_items', 'invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
